version: "3"
services:
  exporter:
    image: ghcr.io/forticheprod/sidefx-lic-exporter:latest
    command:
      - --config=/etc/sidefx-lic-exporter/config.yml
    restart: unless-stopped
    ports:
      - "9102:9102"
    volumes:
      - "./config.yml:/etc/sidefx-lic-exporter/config.yml"
      - "./hfs-bin/hserver:/usr/local/bin/hserver"
      - "./hfs-bin/sesictrl:/usr/local/bin/sesictrl"
